version: '3.9'
services:
  app:
    image: 'docker-spring-boot-mysql:latest'  # Change the image name accordingly
    build:
      context: .
    container_name: app
    depends_on:
      mysql-db:
          condition: service_healthy

    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/springdb  # Change the URL
      SPRING_DATASOURCE_USERNAME: root  # Change the username
      SPRING_DATASOURCE_PASSWORD: 12345  # Change the password

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: springdb  # Change the database name
      MYSQL_ROOT_PASSWORD: 12345  # Change the root password
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 30s
      retries: 15
